version: '3'
services:
  octoprint:
    image: octoprint/octoprint:python3
    container_name: octoprint
    ports:
      - "5000:5000"
    volumes:
      - ./:/octoprint_timelapse_uploader
      - octoprint:/home/octoprint
    command: bash -c "python /octoprint_timelapse_uploader/setup-dev-printer.py && pip install -U -e /octoprint_timelapse_uploader && octoprint serve"
volumes:
  octoprint:
